### ISSUE TITLE
plugin cannot be found in the marketplace

### ISSUE THREAD

**Issue by mtx2d** [vipzhicheng/logseq-plugin-comment-block#1]
Hi Team,
Thanks for creating this plugin.
However when I checked the Marketplace, this plugin does not show up. 

Here is a screenshot of what I can find:
![image](https://user-images.githubusercontent.com/64316805/144542862-6fa5f766-d591-44c7-bd6c-cfb81fa59ad5.png)

**Comment by vipzhicheng** [comment]
Yes, it's still on the road.

**Comment by vipzhicheng** [comment]
It's on the market place now, so I closed this issue.
