### ISSUE TITLE
Structure/order

### ISSUE THREAD

**Issue by crendl** [vipzhicheng/logseq-plugin-comment-block#2]
May I suggest a slightly different order of the bullet points, to avoid a repetition of the block reference?

Instead of:
* Comments
* * Dec. 6th
* * * Project X reference
* * * * comment a
* * * * comment b
* * Dec. 10th
* * * Project X reference
* * * * comment c
* * * * comment d

I would suggest:
* Comments
* * Project X reference
* * * Dec. 6th
* * * * comment a
* * * * comment b
* * * Dec. 10th
* * * * comment c
* * * * comment d

**Comment by vipzhicheng** [comment]
I think providing two modes at the same time is not a good idea, by the way, you can click the ref block and see the specific block comments in the linked reference section.
