### ISSUE TITLE
Duplicate Comment Block

### ISSUE THREAD

**Issue by Willz7** [vipzhicheng/logseq-plugin-comment-block#3]
Hi @vipzhicheng, awesome plugin!!

Recently, I have been receiving duplicate comments since I started using your plugin a few of days ago.

[](url)
![comment](https://user-images.githubusercontent.com/5053219/146275055-439912da-19c0-4143-987a-e4a7437c3894.PNG)

![comment block](https://user-images.githubusercontent.com/5053219/146275288-63769ce0-dfea-49ba-baec-daf7558702cf.PNG)

**Comment by vipzhicheng** [comment]
Can you please provide a demo md file for me to dig into?

**Comment by Willz7** [comment]
> Can you please provide a demo md file for me to dig into?
[logseq_local_D__tester-logseq_markdown_1639875029.zip](https://github.com/vipzhicheng/logseq-plugin-comment-block/files/7740181/logseq_local_D__tester-logseq_markdown_1639875029.zip)

Here is a demo md that I tried it with, and you can see the same issue that I sent in the previous message. 

I think the issue is when I first download the plugin and install it. It shows the two comment block. I am using window 10.

Made a video below of installing the plugin and seeing my experience
https://user-images.githubusercontent.com/5053219/146660265-90b457c2-994a-43e4-88ad-1a6721982cea.mp4


@vipzhicheng

**Comment by vipzhicheng** [comment]
Still can not reproduce this issue, so to close it. If it still happen and has a clear path to reproduce, I will dig into again.
